backend:
  host: "0.0.0.0"
  port: 6666
  ssl: false
  ssl_cert: ""
  ssl_key: ""
  log_level: "INFO"
  main_log_file: "main.log"
  access_log: "[${time}] ${status} - ${latency} ${method} ${path}\n"
  access_log_path: "access.log"
  accept_authorization: null
  accept_user_agent: null
  api_cache_ttl: "300s"
  enable_trust_proxy: true
  trusted_proxies:
    - "127.0.0.0/8"
    - "::1/128"
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "100.64.0.0/10"
    - "10.0.0.0/8"
  proxy_header: "X-Forwarded-For"

chunithm:
  enabled: true
  music_db_type: "mysql"
  music_db_url: "user:password@tcp(localhost:3306)/chunithm_music?parseTime=True&loc=Local"
  binding_db_type: "mysql"
  binding_db_url: "user:password@tcp(localhost:3306)/chunithm?parseTime=True&loc=Local"

pjsk:
  enabled: true
  db_type: "mysql"
  db_url: "user:password@tcp(localhost:3306)/pjsk?parseTime=True&loc=Local"

redis:
  host: "localhost"
  port: 6379
  password: ""

censor:
  baidu_api_key: ""
  baidu_secret: ""
  censor_db_type: "mysql"
  censor_db_url: "user:password@tcp(localhost:3306)/censor?parseTime=True&loc=Local"

haruki_bot:
  db_type: "mysql"
  db_url: "user:password@tcp(localhost:3306)/bot?parseTime=True&loc=Local"
  register_verify_token: ""
  credential_sign_token: ""
  login_sign_token: ""

users_db:
  db_type: "mysql"
  db_url: "user:password@tcp(localhost:3306)/users?parseTime=True&loc=Local"
